"""create accounts and cellar

Revision ID: 20260729_0002
Revises: 20260728_0001
Create Date: 2026-07-29 11:02:29.232406

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260729_0002"
down_revision: str | Sequence[str] | None = "20260728_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "phone_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "scene", sa.Enum("LOGIN", "BIND_PHONE", name="sms_scene"), nullable=False
        ),
        sa.Column(
            "code_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "device_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("failed_attempts >= 0", name="ck_sms_codes_failed_attempts"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sms_codes_created_at"), "sms_codes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sms_codes_device_hash"), "sms_codes", ["device_hash"], unique=False
    )
    op.create_index(
        op.f("ix_sms_codes_expires_at"), "sms_codes", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_sms_codes_ip_address"), "sms_codes", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_sms_codes_phone_hash"), "sms_codes", ["phone_hash"], unique=False
    )
    op.create_index(op.f("ix_sms_codes_scene"), "sms_codes", ["scene"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "phone_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "phone_masked", sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BANNED", "DELETED", name="user_status"),
            nullable=False,
        ),
        sa.Column("age_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("memory_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "membership_level",
            sa.Enum("FREE", "MEMBER", name="membership_level"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_hash", name="uq_users_phone_hash"),
    )
    op.create_index(op.f("ix_users_phone_hash"), "users", ["phone_hash"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "cellar_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ingredient_key", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True
        ),
        sa.Column(
            "custom_name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True
        ),
        sa.Column(
            "normalized_custom_name",
            sqlmodel.sql.sqltypes.AutoString(length=80),
            nullable=True,
        ),
        sa.Column(
            "amount_label", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "source",
            sa.Enum("MANUAL", "LOCAL_SYNC", name="cellar_item_source"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(ingredient_key IS NOT NULL AND custom_name IS NULL AND normalized_custom_name IS NULL) OR (ingredient_key IS NULL AND custom_name IS NOT NULL AND normalized_custom_name IS NOT NULL)",
            name="ck_cellar_items_identity",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cellar_items_user_id"), "cellar_items", ["user_id"], unique=False
    )
    op.create_index(
        "uq_cellar_items_active_custom_name",
        "cellar_items",
        ["user_id", "normalized_custom_name"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND normalized_custom_name IS NOT NULL"
        ),
    )
    op.create_index(
        "uq_cellar_items_active_ingredient",
        "cellar_items",
        ["user_id", "ingredient_key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND ingredient_key IS NOT NULL"),
    )
    op.create_table(
        "user_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "installation_id_hash",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "platform",
            sa.Enum("IOS", "ANDROID", "WEB", name="device_platform"),
            nullable=False,
        ),
        sa.Column(
            "device_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False
        ),
        sa.Column(
            "app_version", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "installation_id_hash", name="uq_user_devices_installation"
        ),
    )
    op.create_index(
        op.f("ix_user_devices_user_id"), "user_devices", ["user_id"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "nickname", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column("avatar_media_id", sa.Uuid(), nullable=True),
        sa.Column(
            "avatar_key", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False
        ),
        sa.Column(
            "signature", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column(
            "occupation", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True
        ),
        sa.Column(
            "school", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True
        ),
        sa.Column(
            "visibility",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column(
            "refresh_token_hash",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["user_devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "refresh_token_hash", name="uq_auth_sessions_refresh_token_hash"
        ),
    )
    op.create_index(
        op.f("ix_auth_sessions_device_id"), "auth_sessions", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"),
        "auth_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_refresh_token_hash"),
        "auth_sessions",
        ["refresh_token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(
        op.f("ix_auth_sessions_refresh_token_hash"), table_name="auth_sessions"
    )
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_device_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_devices_user_id"), table_name="user_devices")
    op.drop_table("user_devices")
    op.drop_index(
        "uq_cellar_items_active_ingredient",
        table_name="cellar_items",
        postgresql_where=sa.text("deleted_at IS NULL AND ingredient_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_cellar_items_active_custom_name",
        table_name="cellar_items",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND normalized_custom_name IS NOT NULL"
        ),
    )
    op.drop_index(op.f("ix_cellar_items_user_id"), table_name="cellar_items")
    op.drop_table("cellar_items")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_phone_hash"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sms_codes_scene"), table_name="sms_codes")
    op.drop_index(op.f("ix_sms_codes_phone_hash"), table_name="sms_codes")
    op.drop_index(op.f("ix_sms_codes_ip_address"), table_name="sms_codes")
    op.drop_index(op.f("ix_sms_codes_expires_at"), table_name="sms_codes")
    op.drop_index(op.f("ix_sms_codes_device_hash"), table_name="sms_codes")
    op.drop_index(op.f("ix_sms_codes_created_at"), table_name="sms_codes")
    op.drop_table("sms_codes")
    bind = op.get_bind()
    for enum_name in (
        "cellar_item_source",
        "device_platform",
        "membership_level",
        "sms_scene",
        "user_status",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
